PROTOCOL_STATE_GET_FULL_FILE_STRUCTURE = 1
PROTOCOL_STATE_SEND_FULL_FILE_STRUCTURE = 2
PROTOCOL_STATE_GET_FILE = 3
PROTOCOL_STATE_SENDING_FILE = 4
PROTOCOL_STATE_SENDING_FILE_FINISHED = 5
PROTOCOL_STATE_REQUIREMENT_FINISHED = 6
SYNC_FOLDER = 'db'
CLIENT_SYNC_FOLDER = 'cdb'